# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('orderhelper', '0029_auto_20160227_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnizor',
            name='group',
            field=models.ManyToManyField(related_name='furnizors', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='persoana',
            name='group',
            field=models.ManyToManyField(related_name='persoanas', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='producator',
            name='group',
            field=models.ManyToManyField(related_name='producators', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='reper',
            name='group',
            field=models.ManyToManyField(related_name='repers', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='group',
            field=models.ManyToManyField(related_name='subcomandas', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 27, 8, 51, 48, 737853, tzinfo=utc), verbose_name='Data'),
        ),
    ]
